kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: db
  name: db-ingress-calico
spec:
  podSelector:
    matchLabels:
      app: db
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: frontend
          podSelector:
            matchLabels:
              app: result
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: backend
          podSelector:
            matchLabels:
              app: worker           
      ports:
        - protocol: TCP
          port: 5432
